### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by magicmonty** [picklesdoc/pickles-testresults#18]
Just for understanding. What is the point in having this test harness outside of the Pickles-Repository?

**Comment by dirkrombauts** [comment]
Good question. I guess back then I was in a "one solution per repository" mood. I'm not so sure about it anymore now. Where would you expect to find it?

**Comment by magicmonty** [comment]
I would expect it to find under `TestHarness` or `test` in the repository where the tests are (in this case in the pickles repo).

here I needed to make two pull requests for a single bug.

Also If you put the Test harness side by side into the pickles repository, you  could generate the TestResult XMLs on the fly in the CI build. Currently they contain machine- and user-specific data which is of no interest for the tests.

**Comment by dirkrombauts** [comment]
So for example at as a subdirectory of [`src`](https://github.com/picklesdoc/pickles/tree/develop/src), on the same level with Pickles?

**Comment by magicmonty** [comment]
No, I would make a `test` directory on the same level as the `src` directory and put it there.

**Comment by dirkrombauts** [comment]
fine by me but we'll have to call it something else then - the test.fsx script creates a "test" directory. How about `testresults'?

**Comment by magicmonty** [comment]
Yeah sounds better

**Comment by magicmonty** [comment]
I think this can be closed now, that the test harness has moved into the pickles repo.
